### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by Squeezya** [TheBeastLT/torrentio-scraper#113]
Hi, I've been trying to run this repo locally and to do so I've made the following steps:

- create a `.env` file with `DATABASE_URI` for a local postgres db.
- add `const dotenv = require("dotenv"); dotenv.config();` to the beginning of `addons/index.js`
- run `database.sync({ alter: true });` from Sequelize after defining the models on `addons/lib/repository.js`.

The server seems to startup nicely, I am able to add the local running addon to stremio, but I never get any result for any movie/serie/anime.

I tried running both the `catalogs` and `addons` but the result seems the same.

I though that the database would get populated automatically when no hash was found, did I assume wrong?
Could you shed some light on what I should be doing to make this work?

Thanks

**Comment by TheBeastLT** [comment]
Hi, database is populated by a different process, which periodically scrapes various providers for new torrents and indexes them. This code is not part of this repo due to dmca concerns.
This whole repo/idea is architectured to be an efficient remote addon/api. It's not really meant to be run locally.
