### ISSUE TITLE
Request - Audio Language preferences

### ISSUE THREAD

**Issue by boomoliver** [TheBeastLT/torrentio-scraper#154]
Theres already a "Priority foreign language" option which is nice, but it would be really great with a tab to choose only the language audio you want, and exclude everything else, similar to orion. Since for anime, it feels like 80% of it is in japanese (non-dubbed), and usually only 1 or 0 dubbed option shows up when the max results are 5. Would really make it easier to find dubbed versions for people like me that dont like subbed. Would also make it way easier to find stuff dubbed in your home language, which is much more comfortable for some people. The fact theres no option to choose and exclude languages is the only reason I still use orion for most of that stuff.

**Comment by andronedev** [comment]
This is a good idea because when I look for a torrent in the language and it is not in the debrid cache I have to scroll for a long time to find the Real debrid download because between those in the cache in my language and those which are in my language but not in cache and well there are all the other languages

**Comment by andronedev** [comment]
This is a good idea because when I look for a torrent in the language and it is not in the debrid cache I have to scroll for a long time to find the Real debrid download because between those in the cache in my language and those which are in my language but not in cache and well there are all the other languages

**Comment by TheBeastLT** [comment]
Similar suggestion was already discussed at #64
