### ISSUE TITLE
[Request] - Scrape Sports Events

### ISSUE THREAD

**Issue by Ned-Flanders** [TheBeastLT/torrentio-scraper#166]
Hi,

Just to start this by saying this is a fantastic add on and thank you for the work the devs have done. 

Would it be possible to add a feature where torrentio can scrape sports events? I have a Trakt list of UFC events but when I select it, for example, UFC 295. It says “No addons were requested for the stream”. I can see there are torrents available for the vod on sites like ThePirateBay which I believe torrentio does scrape from.

At the moment, I manually add the torrent VOD to RD and then use the add on “Debrid Search” to watch it on stremio, but it would be a lot easier if torrentio could scrape it for me.

Thanks!

**Comment by TheBeastLT** [comment]
They are scraped, problem is that they are matched based on imdb id, and not always the event has an imdb or it matched to it since they are very similar in name only the number differs. I don't see a solution for this, only manually reassigning the imdb ids for such entries, but that would be too much work, so I'm don't have plans to work on this.
