### ISSUE TITLE
Debrid-link support

### ISSUE THREAD

**Issue by LukinFilch** [TheBeastLT/torrentio-scraper#19]
Hello,

It is possible to add the support of Debrid-link ? They have hosts and torrents like other debrid services.

Thanks for your amazing work, I have migrated from Kodi and that work better 👍

**Comment by TheBeastLT** [comment]
Hey, thanks for the suggestion! There's quite a few debrid clients implemented already, but might look into adding this one as well in there's more people using/requesting it, as it's API is a bit different from the others (uses OAuth for authentication, instead of API key, so it would take a bit more time to implement).

**Comment by LukinFilch** [comment]
Following your message I asked them to add the API key and they told me that it was done.

**Comment by cluttere45** [comment]
I am also interested by debrid-link, I can try to write script by copying the others.

**Comment by TheBeastLT** [comment]
@cluttere45 Sure, you can try it out :+1:

**Comment by TheBeastLT** [comment]
If there's a possibility to create a separate apikey (which you could revoke later on) and some could share it to me through discord I could take a look in adding support for it.

**Comment by cluttere45** [comment]
@TheBeastLT Works perfectly, you are the best.
