### ISSUE TITLE
Web.stremio playback issue with real debrid on torrentio

### ISSUE THREAD

**Issue by Jamescsthowards** [TheBeastLT/torrentio-scraper#190]
Most streams will play without volume or sometimes with no video and just audio. But this doesn't happen with watching videos directly from real debrid in safari. Even 4K remux.There's another site called debridmediamanager that lets you stream 4K remux from rd in safari. Not sure if that's something you can fix to have web.stremio.com to play all links properly without needing VLC app from torrentio. But either way thanks for creating such an amazing addon

**Comment by TheBeastLT** [comment]
RD internal player pays not the actual file, but a re-encoded video file, that is usually supported by the browser (which has usually lower quality). There was some effort (#36) to make addon return this url instead of the original file, but that video would fail to play in current stremio player, so it was removed
