### ISSUE TITLE
Add EternalAnimes tracker

### ISSUE THREAD

**Issue by mrcanelas** [TheBeastLT/torrentio-scraper#21]
Hello, would it be possible to add the tracker for a Brazilian fansub? 
https://nyaa.si/user/EternalAnimes

**Comment by TheBeastLT** [comment]
Hey, thanks for the suggestion. When adding nyaa.si I've decided to exclude non-english category, as for a lot of the entries there it's impossible to determine the language from the title. Though maybe it would be possible to use the uploader to decide the language, as they seem to upload for the same language always.

The other thing is, I haven't decided how to proceed with non-english entries in general, since there's a lot of people who don't want to see non-english content. Adding a filter for that might be hard as it could filter out false positives and etc, where it would could remove torrents which have dual audio or just subs in different lang... Of course there are the flags displayed in Stremio responses, so users can differentiate between different langs, but like I said haven't decided yet if that's enough of an indicator for a good experience for most users.

**Comment by mrcanelas** [comment]
I think that you determine the language by the name of the FanSub, this value between [], the question of showing languages in others can be a problem for some, for me it is not, I do not know if it is interesting for you to transform Torrentio into an SDK, so whoever wants content in other languages can add the trakers that interest him and set up an addon.
