### ISSUE TITLE
Has torrentio gone down? 

### ISSUE THREAD

**Issue by whynotcustombuilds** [TheBeastLT/torrentio-scraper#24]
Has torrentio gone down? I noticed it is not in the community add-ons, except torrentio lite, but any thing I watch from there either doesn't work anymore or plays for a couple of minutes and stops, any help would be appreciated.

**Comment by TheBeastLT** [comment]
Hey, everything is working fine. The addon only returns indexed torrent infohashes, it does not store/control the content. So it depends on many factors why you could have problems, most often it's due to low seeders or problems on your network.
Also you can always configure/install the addon from http://torrentio.strem.fun/

**Comment by hugox66** [comment]
I think torrentio is down
