### ISSUE TITLE
Scraping RD isn't complete

### ISSUE THREAD

**Issue by oleglucic** [TheBeastLT/torrentio-scraper#282]
Users that have connected RD might have experienced this. For example. Open Tomorrowland (2015) and you'll see 4K HDR, 4K and 720p. I wanted to cache 1080p so the users can stream that version too. When i tried to cache it, RD pushed notification that the file is already on their servers. I was confused because it couldn't be seen in Stremio and is from one of the sources that torrentio scrapes from. Just to double check, I searched on Torrentio without RD and have found the exact same file, just this one wasn't cached.  I don't really know what's going on, but this issue persists on much more content. Hope this gets resolved : )

Thank you for your work!

**Comment by TheBeastLT** [comment]
Cached statuses are cached (on addon's side) and so are the responses users see, so it might be that you that entry was recently added to RD and is not reflected in the results due to caching. Also there are cases where RDs API returns that some entries are not cached when they actually are (and also vice-versa can happen), so there's no much to do here.
