### ISSUE TITLE
addon for Portuguese Portugal

### ISSUE THREAD

**Issue by tkiterio** [TheBeastLT/torrentio-scraper#35]
hi, in your code for brazuca you have the flag from PORTUGAL and not flag portuguese brazilian. but I don't know if it's important, I think they automatically put the flag of Portugal.
Movie in portuguese brazilian is not the same of Portuguese Portugal. i think there should be a distinction or called by the correc name on the language option "Portuguese brazilian" .
and is possible to add search torrent with language Portuguese portugal, normally on the name the torrents is written "Portuguese"  or "ENG.PT" or "PT.ENG" or just PT basicaly are animation. the portuguese dont make dub for all movies like brazilian,french and spanish. we like watch in the language they were made except animation...

thanks for all work on this adddon

sorry for my english, if you if you want you can delete this.

**Comment by TheBeastLT** [comment]
Hi, I can understand your concern, but it's unlikely this will change. Detecting whether it Pt Brazillian or simple Pt, is hard since in a lot of cases they just write Pt/Portuguese. So they are both grouped together, because if you'd try to differentiate between these 2 you'd get an incomplete/incorrect results (ie. the torrent name includes just Portuguese, but it's actually Pt-Br and user chose to see only Pt-Br so he won't see this entry).
With grouping at least you can pre-filter entries which are possible candidates and then you can choose the right language from them based on name/provider and ect.
