### ISSUE TITLE
Put.io support

### ISSUE THREAD

**Issue by PileofBoxes** [TheBeastLT/torrentio-scraper#6]
Not a issue just a feature request 

I was hoping you could add put.io support 
Thanks so much for this awesome app it's crazy how fast it is much appreciated

**Comment by TheBeastLT** [comment]
Hey, not sure what you had in mind for put.io feature, but from a quick glance it's a file storage service?

**Comment by PileofBoxes** [comment]
Put.io is cloud storage with torrent support they cache torrents just like real debrid 
you send a torrent/magnet link to put.io 
it gets saved to your cloud storage instantly if some other user downloaded the same torrent before because it's cached 
But for that very reason it's very reliable they hold on to files for very long time it seems.

I been dreaming  for put.io support  auto scraping for a very long time  in other programs such as Kodi
but most people oddly want real debrid support & Premiumize.me

But I honestly think put.io is a 
A Diamond in the Rough
When it comes to cached data 

It's
cross platform for Apple TV and iPhone and windows and ruku and even Kodi on Xbox one 

They even convert the torrent files to mpeg-4 so it will play on all devices if needed 


If you need to test it out I can give you a free invite on my family plan 

Thanks so much for this add-on on regardless of put.io support this is honestly pretty remarkable it's just so fast and clean

**Comment by TheBeastLT** [comment]
Thanks for the info!
Briefly looked at their API, and it seems there are a few problems:
 - No endpoint to check cached torrents availability. Seems it's only possible to know it once you add the torrent for downloading.
 - `The returned URL contains an authentication token that is only valid from the IP address that this request is made.` If this is true then it would be a deal breaker, as it wouldn't be possible to use it with a remote addon, as the resolved url won't be usable by the user.

I have plans in the future to add premiumize support, so once I'm implementing that I might look into this further if this would be possible.

**Comment by PileofBoxes** [comment]
Thanks for checking much appreciated

**Comment by TheBeastLT** [comment]
Hey @PileofBoxes , I'm currently working on implementing other debrid integrations and might have a look a put.io. It be great if you could invite me to test it out. You can reach out to me regarding this on addons discord or reddit.

**Comment by TheBeastLT** [comment]
Hey, I've added initial implementation for put.io support. You'll have to create a new OAuth application in your account and provide it's `clientId` and `token` in the addon configuration page.
The integration links will only be available when `Show download to debrid links for uncached` debrid option is selected. There it will show a download link for each torrent. Only on selecting a specific torrent it is possible to know if it's cached or not. If it cached a video stream will be returned, if not the torrent will start downloading on put.io.
The resolving can be a bit slow, as it involves a lot of steps for put.io, and was a bit trickier to implement so let's see how it goes.
The implementation uses the public sharing feature, as otherwise the links are bound to the remote IP where it was resolved. Using this feature you can have only 10 shared videos, so when exceeding this limit, the addon will delete the last shared link. So if you're using this feature be aware.

Cheers!
