### ISSUE TITLE
[Request] Option to disable showing HDR.

### ISSUE THREAD

**Issue by Zero0Q** [TheBeastLT/torrentio-scraper#67]
Hi, could you add a option to hide or not showing HDR files when searching? 
Thanks

**Comment by TheBeastLT** [comment]
No, adding configuration options should only be for important things, since otherwise it will confuse and make it harder to maintain this addon.

**Comment by Bananaman** [comment]
@TheBeastLT This is something that would help us a lot...

In two ways.

## Reason 1:

The Chromecast with Google TV is the most recommended media player for Stremio...

If you connect it to a NON-HDR TV and you try to play HDR content in Stremio, then Stremio almost crashes. The decoding slows down to around 1 FPS.

So people with SDR TVs must painstakingly scroll past every HDR video that Torrentio puts in Stremio.

## Reason 2:

Having an option to filter out unsupported formats makes the stream selection list kuch smaller and more efficient to navigate. Which is especially important now due to Stremio's redesign for Android TV where every stream is a HUGE button and very slow to scroll through to find the store that is compatible with your device.

It might be good to implement a "Format Filter" setting with checkboxes for HDR and 4K, which are the two things that people would benefit from removing depending on their devices.

- Removing HDR to fix ugly playback (at best) or crashing Stremio on SDR devices.
- Removing 4K if you only have a 1080p device and don't want to waste bandwidth.

The question isn't if this feature is a good thing. My only real question is: Should this filtering be in Torrentio, or in Stremio?

If Torrentio somehow exports Metadata about each stream (HDR, 4k Etc) then I think Stremio should do the filtering.

If it just exports a plaintext title, description and stream URL then I think the addon protocol should be extended to allow more details so that Stremio can filter it. Or as a last resort implementing the filtering in Torrentio directly.

**Comment by Bananaman** [comment]
After talking to Stremio's lead developer, I realized that this is not a job for Stremio for 1 reason:

Addons don't provide accurate data. So there is no point in filtering about it.

Torrentio relies on scanning filenames for tags. A movie might be named "Movie 2022 Blu-ray" and Torrentio would have no way to know that it contains DV/HDR. So there are no guarantees that a lack of a HDR tag in Torrentio means that it's not HDR.

Therefore, the suggestion went back here instead and the answer was basically "the addon should filter out those results".

Torrentio can at least scan for and remove HDR and TV results. It would not be accurate enough to be an official feature in Stremio itself. But definitely good enough to be a removal feature in Torrentio. Something like "Hide movies with tags: HDR, DV, 4K".

**Comment by TheBeastLT** [comment]
@Bananaman I've added ability to exclude any of the HDR types (HDR/HDR10+/DV) or only DV  when it's the single HDR profile available.

> and 4K (anything tagged 4K/2160p).

This was already possible, in config you can select to exclude 4k quality.

**Comment by Bananaman** [comment]
@TheBeastLT Hey, I thought I already replied to you earlier, apologies!

I am incredibly grateful that you added the filtering. I am seriously thankful. You're awesome! My parents are now able to use Stremio without so much risk of crashing! In fact, Google came up with a new OS update which fixes the crash when tonemapping HDR to SDR TVs, but the HDR movies look absolutely terrible (color artifacts etc) due to bad tonemapping, so even though the crashes are now fixed, this new feature still makes all movies/shows look way better since the chance that my parents pick a SDR stream is now closer to 100% thanks to your filters! :) I love you.
