### ISSUE TITLE
Request to add https://tamilblasters.casa/ as provider

### ISSUE THREAD

**Issue by Rmz23** [TheBeastLT/torrentio-scraper#74]
Hello, a small request to add https://tamilblasters.casa/ as provider. They have a large and very updates database of Indian and English Content. 
Someone has already made a scraper ( addon linked attached below)
https://github.com/mhdzumair/tamilblasters_streamio_addon
But would love to download via RD

**Comment by KARANRSB** [comment]
So thebeastlt I didn't know there is a duplicate issue but can u please add it bro?
I just love using torrentio for my hollywood stuff best addon there is on the market all because of you but for Indian content it would be amazing if u did add it man I know u have other addons in your mind but please consider this one also thank you.

**Comment by jrjaggari** [comment]
Is this issue being worked on?

**Comment by Rmz23** [comment]
> Is this issue being worked on?

Use this addon, they have now added real debrid and seedr support

https://github.com/mhdzumair/tamilblasters_stremio_addon

**Comment by kalyanrajnish** [comment]
[https://www.1tamilblasters.tel/](url)
is the new link

**Comment by TheBeastLT** [comment]
I think https://github.com/mhdzumair/MediaFusion addon fills this request well and has much more Indian content, so I consider it a better alternative than adding it to Torrentio
