### ISSUE TITLE
Foreign contents from tmdb with RARBG

### ISSUE THREAD

**Issue by teemokin** [TheBeastLT/torrentio-scraper#80]
Hello.
First off, thanks for the addon and I really like it.
When I search foreign contents from TMDB, torrentio seems not to parse torrents from Rarbg.
I'm not sure but from my experience every rarbg's torrent is uploaded in English titles. So I have to use the English title when I search.
But I guess Torrentio is searching with the original title because I can see the torrent properly when I manually search for the English title on Rarbg.
This is just my rough guess, so I might be wrong.

**Comment by TheBeastLT** [comment]
It's not clear what you're searching for or what your problem is here. Torrentio is not related to TMDB and does not use it. If you're talking about TMDB addon, not every title in TMDB has a mapping to an IMDB title, which is needed to retrieve links from Torrentio.
Anyways, this is in no case related to Torrentio addon itself so I'll close it.

**Comment by teemokin** [comment]
Thank you. now I totally understand. And do you have any plans to add a function to search torrents using TMDB id?

**Comment by TheBeastLT** [comment]
> Thank you. now I totally understand. And do you have any plans to add a function to search torrents using TMDB id?

No, I have no plans for it,since it works fine 99.99% of times and tmdb entries have imdb id mapped.

**Comment by teemokin** [comment]
ok I see. it's kinda sad imdb does not deal with non-English-content much, so it is difficult to search torrents with it ToT. btw thanks for the information and the add-on. 👍
